name: solana_pay
description: Create transaction and payment requests using Solana Pay
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.17.1 <3.0.0'

dev_dependencies:
  solana: ^0.25.0
  lints: ^2.0.0
  test: ^1.16.0
