name: solana_pay
description: Create transaction and payment requests using Solana Pay
version: 1.0.0
repository: https://github.com/cpellet/solana-pay

# homepage: https://www.example.com

environment:
  sdk: '>=2.17.1 <3.0.0'

dependencies:
  solana: ^0.25.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
